
# Define target output
target: vcs

export PRJ_VERSION = "DA100416"

# Define target part
export PRJ_PART = XC7Z045FFG900-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk

