
## Get Environment Variables
set SOURCE_FILE $::env(SOURCE_FILE)
set XDC_FILES   $::env(XDC_FILES)
set PRJ_PART    $::env(PRJ_PART)
set PROJECT     $::env(PROJECT)
set PROJ_DIR    $::env(PROJ_DIR)

## Run source file commands
source $SOURCE_FILE

## Read XDC FILES
read_xdc $XDC_FILES

## Synthesize
synth_design -top $PROJECT -part $PRJ_PART
write_checkpoint -force ${PROJECT}_post_synth_.dcp

## Debug
source ${PROJ_DIR}/vivado/debug_test.tcl

## Optimize
opt_design

## Place
place_design
write_checkpoint -force ${PROJECT}_post_place.dcp
report_utilization -file ${PROJECT}_post_place_util.txt

## Route
route_design

## Reports are not generated by default
report_timing_summary -file ${PROJECT}_post_route_timing.txt

## Save the database after post route
write_checkpoint -force ${PROJECT}_post_route.dcp

## Check for DRC
report_drc -file ${PROJECT}_post_route_drc.txt

## Write Bitstream
write_bitstream -force ${PROJECT}.bit 

