# Define Firmware Version Number
export PRJ_VERSION = 0xDA100416

# 412 = stable axis v2
# 413 = axis v1 cache setting test

# Define target output
target: bit

export GIT_BYPASS = 1

# Define target part
export PRJ_PART = XC7Z045FFG900-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
